FROM jupyter/base-notebook:python-3.11

USER root

# Install Java (required for PySpark)
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Install matching PySpark version
RUN pip install pyspark==3.5.1
RUN pip3 install numpy pandas matplotlib seaborn scikit-learn
USER $NB_UID
